version: '3.9'

services:
  pg:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_UID}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
      POSTGRES_DB: ${POSTGRES_DBS}
    ports:
      - "5435:5432"
    volumes:
      - proj_de_globantpos_pgdata:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_UID} -d ${POSTGRES_DBS}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  app:
    build: .
    container_name: proj_de_globantpos_app
    depends_on:
      pg:
        condition: service_healthy
    environment:
      POSTGRES_UID: ${POSTGRES_UID}
      POSTGRES_PWD: ${POSTGRES_PWD}
      POSTGRES_DBS: ${POSTGRES_DBS}
      POSTGRES_HST: ${POSTGRES_HST}
      POSTGRES_POR: ${POSTGRES_POR}
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  proj_de_globantpos_pgdata:
  app:
